theme: jekyll-theme-minimal
title: My FreeCAD activity
description: A little blog to sumarize my FreeCAD-activity. *Support me via [liberapay](https://de.liberapay.com/looooo/)*
logo: tandem_and_me.jpg
